on:
  release:
    types: [created]

jobs:
  build:
    name: Release Go Binary
    runs-on: ubuntu-latest
    container:
      image: golang:1.22.4
    steps:
      - uses: actions/checkout@v2
      - run: sh ./make.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/ottp-feedback_linux-arm_dev-23c6f79.tgz
            release/ottp-feedback_linux-arm64_dev-23c6f79.tgz
            release/ottp-feedback_windows-amd64_dev-23c6f79.tgz